extends Node
## Icon-coverage harness (v0.2.0 art/UI sprint).
##
## Asserts the item-icon guarantees from the sprint spec:
##   1. Every id in items.json (except the alias D06) has an icon PNG on disk that
##      resolves to a real Texture2D (not the defensive category-square fallback).
##   2. ItemDB.icon(id) is non-null for every id, and the alias D06 resolves to the
##      SAME texture as its canonical I4 (D06 → I4's icon).
##   3. No two icon FILES are byte-identical — i.e. 68 canonical icons are all
##      unique (the only allowed duplicate is D06.png == I4.png, the alias copy).
##
## Prints PASS/FAIL lines and quits with the failure count as the exit code.

const ICON_DIR := "res://assets/icons/"
const ITEMS_PATH := "res://data/items.json"

var _fail := 0


func _check(label: String, cond: bool) -> void:
	print("[%s] %s" % ["PASS" if cond else "FAIL", label])
	if not cond:
		_fail += 1


func _ready() -> void:
	print("=== ICON COVERAGE HARNESS ===")

	var records := _load_records()
	_check("items.json loaded (>=69 records)", records.size() >= 69)

	# Split canonical vs alias. (L2-4) Layer-2 items (layer:2) now have bespoke science-family
	# icons (J1-J7 + D62-D102 = 48 files), generated by tools_gen_icons.js alongside the 68
	# Layer-1 painted icons. Both sets are held to the same file-present + non-null + byte-unique
	# contract below.
	var canonical_ids: Array[String] = []       # Layer-1 canonical (icon-covered)
	var l2_ids: Array[String] = []              # Layer-2 canonical (icon-covered, L2-4)
	var l3_ids: Array[String] = []              # Layer-3 canonical (icon-covered, L3-4)
	var alias_ids: Array[String] = []
	for rec: Dictionary in records:
		var id := String(rec.get("id", ""))
		if id == "":
			continue
		if rec.has("alias_of"):
			alias_ids.append(id)
		elif int(rec.get("layer", 1)) == 2:
			l2_ids.append(id)
		elif int(rec.get("layer", 1)) == 3:
			l3_ids.append(id)
		else:
			canonical_ids.append(id)
	# (L3-4) Layer-3 clockwork items: K1-K7 (7 gather) + D103-D139 (37 craft) = 44 bespoke icons.
	_check("68 Layer-1 + 48 Layer-2 + 44 Layer-3 canonical + 1 alias split",
		canonical_ids.size() == 68 and l2_ids.size() == 48 and l3_ids.size() == 44 \
		and alias_ids.size() == 1)

	# 1. every canonical id (Layer-1, -2, -3) has a real icon FILE (present on disk).
	var missing: Array[String] = []
	for id in canonical_ids + l2_ids + l3_ids:
		if not ResourceLoader.exists(ICON_DIR + id + ".png"):
			missing.append(id)
	_check("every canonical id (L1+L2+L3) has an icon PNG (missing=%s)" % [missing], missing.is_empty())

	# 2. ItemDB.icon(id) non-null for every id (canonical + L2 + L3 + alias).
	var null_ids: Array[String] = []
	for id in canonical_ids + l2_ids + l3_ids + alias_ids:
		if ItemDB.icon(id) == null:
			null_ids.append(id)
	_check("ItemDB.icon() non-null for all ids (null=%s)" % [null_ids], null_ids.is_empty())

	# 2b. Layer-2 + Layer-3 icons resolve to a REAL painted file, not the category fallback square.
	# (ItemDB.icon returns a fallback ImageTexture when the PNG is absent; assert the PNG exists
	# AND load() succeeds so those items are genuinely covered, not silently squared.)
	var l2_fallback: Array[String] = []
	for id in l2_ids + l3_ids:
		if not ResourceLoader.exists(ICON_DIR + id + ".png") or load(ICON_DIR + id + ".png") == null:
			l2_fallback.append(id)
	_check("all 92 Layer-2+3 icons are real painted files (fallback=%s)" % [l2_fallback], l2_fallback.is_empty())

	# alias D06 resolves to I4's icon (same texture object / same file).
	var d06 := ItemDB.icon("D06")
	var i4 := ItemDB.icon("I4")
	_check("D06 icon resolves to I4's icon", d06 != null and d06 == i4)

	# 3. no two icon files byte-identical (160 canonical files all unique: 68 L1 + 48 L2 + 44 L3).
	var hashes := {}
	var dup_pairs: Array = []
	for id in canonical_ids + l2_ids + l3_ids:
		var bytes := _read_bytes(ICON_DIR + id + ".png")
		var h := bytes.get_string_from_ascii() if false else str(bytes.size()) + ":" + _digest(bytes)
		if hashes.has(h):
			dup_pairs.append([hashes[h], id])
		else:
			hashes[h] = id
	_check("all 160 canonical icon files are byte-unique (dupes=%s)" % [dup_pairs], dup_pairs.is_empty())
	_check("distinct icon hashes == 160", hashes.size() == 160)

	# Sanity: the alias file, if present, equals I4's file (spec: D06 shares I4 art).
	if ResourceLoader.exists(ICON_DIR + "D06.png"):
		var a := _read_bytes(ICON_DIR + "D06.png")
		var b := _read_bytes(ICON_DIR + "I4.png")
		_check("D06.png bytes == I4.png bytes (alias copy)", a == b)

	print("=== RESULT: %s (%d failures) ===" % ["PASS" if _fail == 0 else "FAIL", _fail])
	get_tree().quit(_fail)


func _load_records() -> Array:
	var f := FileAccess.open(ITEMS_PATH, FileAccess.READ)
	if f == null:
		return []
	var parsed: Variant = JSON.parse_string(f.get_as_text())
	f.close()
	if typeof(parsed) != TYPE_DICTIONARY:
		return []
	return parsed.get("items", [])


func _read_bytes(path: String) -> PackedByteArray:
	# Read from the actual PNG (source), not the imported .ctex, so byte-identity
	# reflects the generated art.
	var f := FileAccess.open(path, FileAccess.READ)
	if f == null:
		return PackedByteArray()
	var b := f.get_buffer(f.get_length())
	f.close()
	return b


func _digest(bytes: PackedByteArray) -> String:
	var ctx := HashingContext.new()
	ctx.start(HashingContext.HASH_SHA256)
	ctx.update(bytes)
	return ctx.finish().hex_encode()
